/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ttmt.tuan3.Lab2;

/**
 *
 * @author Lâm Hoàng Minh Tuấn
 */
public class ThietkegiaodienCalculator extends javax.swing.JFrame {

    /**
     * Creates new form ThietkegiaodienCalculator
     */
    public ThietkegiaodienCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPnmain = new javax.swing.JPanel();
        JPnmanhinh = new javax.swing.JPanel();
        JLBmanhinh = new javax.swing.JLabel();
        JPnbanphim = new javax.swing.JPanel();
        so1 = new javax.swing.JButton();
        so2 = new javax.swing.JButton();
        so3 = new javax.swing.JButton();
        chia = new javax.swing.JButton();
        canB2 = new javax.swing.JButton();
        so4 = new javax.swing.JButton();
        so5 = new javax.swing.JButton();
        so6 = new javax.swing.JButton();
        nhan = new javax.swing.JButton();
        phantram = new javax.swing.JButton();
        so7 = new javax.swing.JButton();
        so8 = new javax.swing.JButton();
        so9 = new javax.swing.JButton();
        tru = new javax.swing.JButton();
        motphanx = new javax.swing.JButton();
        so0 = new javax.swing.JButton();
        congtru = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        cong = new javax.swing.JButton();
        bang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPnmain.setLayout(new java.awt.BorderLayout());

        JLBmanhinh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLBmanhinh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        JLBmanhinh.setText("0");

        javax.swing.GroupLayout JPnmanhinhLayout = new javax.swing.GroupLayout(JPnmanhinh);
        JPnmanhinh.setLayout(JPnmanhinhLayout);
        JPnmanhinhLayout.setHorizontalGroup(
            JPnmanhinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLBmanhinh, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        JPnmanhinhLayout.setVerticalGroup(
            JPnmanhinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnmanhinhLayout.createSequentialGroup()
                .addComponent(JLBmanhinh, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        JPnmain.add(JPnmanhinh, java.awt.BorderLayout.PAGE_START);

        JPnbanphim.setLayout(new java.awt.GridLayout(4, 5));

        so1.setText("1");
        JPnbanphim.add(so1);

        so2.setText("2");
        JPnbanphim.add(so2);

        so3.setText("3");
        JPnbanphim.add(so3);

        chia.setText("/");
        JPnbanphim.add(chia);

        canB2.setText("sqrt");
        JPnbanphim.add(canB2);

        so4.setText("4");
        JPnbanphim.add(so4);

        so5.setText("5");
        JPnbanphim.add(so5);

        so6.setText("6");
        JPnbanphim.add(so6);

        nhan.setText("*");
        JPnbanphim.add(nhan);

        phantram.setText("%");
        JPnbanphim.add(phantram);

        so7.setText("7");
        JPnbanphim.add(so7);

        so8.setText("8");
        JPnbanphim.add(so8);

        so9.setText("9");
        JPnbanphim.add(so9);

        tru.setText("-");
        JPnbanphim.add(tru);

        motphanx.setText("1/x");
        JPnbanphim.add(motphanx);

        so0.setText("0");
        JPnbanphim.add(so0);

        congtru.setText("+/-");
        JPnbanphim.add(congtru);

        xoa.setText("C");
        JPnbanphim.add(xoa);

        cong.setText("+");
        JPnbanphim.add(cong);

        bang.setText("=");
        JPnbanphim.add(bang);

        JPnmain.add(JPnbanphim, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPnmain, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPnmain, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThietkegiaodienCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThietkegiaodienCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThietkegiaodienCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThietkegiaodienCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThietkegiaodienCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLBmanhinh;
    private javax.swing.JPanel JPnbanphim;
    private javax.swing.JPanel JPnmain;
    private javax.swing.JPanel JPnmanhinh;
    private javax.swing.JButton bang;
    private javax.swing.JButton canB2;
    private javax.swing.JButton chia;
    private javax.swing.JButton cong;
    private javax.swing.JButton congtru;
    private javax.swing.JButton motphanx;
    private javax.swing.JButton nhan;
    private javax.swing.JButton phantram;
    private javax.swing.JButton so0;
    private javax.swing.JButton so1;
    private javax.swing.JButton so2;
    private javax.swing.JButton so3;
    private javax.swing.JButton so4;
    private javax.swing.JButton so5;
    private javax.swing.JButton so6;
    private javax.swing.JButton so7;
    private javax.swing.JButton so8;
    private javax.swing.JButton so9;
    private javax.swing.JButton tru;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables
}
