/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ttmt.tuan3.Lab3;

/**
 *
 * @author Lâm Hoàng Minh Tuấn
 */
public class Thietkegiaodiengamemini extends javax.swing.JFrame {

    /**
     * Creates new form Thietkegiaodiengamemini
     */
    public Thietkegiaodiengamemini() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPnmain = new javax.swing.JPanel();
        JPntren = new javax.swing.JPanel();
        JLBname = new javax.swing.JLabel();
        JPnduoi = new javax.swing.JPanel();
        JBTbatdau = new javax.swing.JButton();
        JPngiua = new javax.swing.JPanel();
        so15 = new javax.swing.JButton();
        so14 = new javax.swing.JButton();
        so13 = new javax.swing.JButton();
        so12 = new javax.swing.JButton();
        so11 = new javax.swing.JButton();
        so10 = new javax.swing.JButton();
        so9 = new javax.swing.JButton();
        so8 = new javax.swing.JButton();
        so7 = new javax.swing.JButton();
        so6 = new javax.swing.JButton();
        so5 = new javax.swing.JButton();
        so4 = new javax.swing.JButton();
        so3 = new javax.swing.JButton();
        so2 = new javax.swing.JButton();
        so1 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Mini");

        JPnmain.setLayout(new java.awt.BorderLayout());

        JLBname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLBname.setText("TRÒ CHƠI XẾP SỐ");
        JPntren.add(JLBname);

        JPnmain.add(JPntren, java.awt.BorderLayout.PAGE_START);

        JBTbatdau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JBTbatdau.setText("Bắt đầu");
        JBTbatdau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTbatdauActionPerformed(evt);
            }
        });
        JPnduoi.add(JBTbatdau);

        JPnmain.add(JPnduoi, java.awt.BorderLayout.PAGE_END);

        JPngiua.setLayout(new java.awt.GridLayout(4, 4));

        so15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        so15.setText("15");
        JPngiua.add(so15);

        so14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        so14.setText("14");
        JPngiua.add(so14);

        so13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        so13.setText("13");
        JPngiua.add(so13);

        so12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        so12.setText("12");
        JPngiua.add(so12);

        so11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        so11.setText("11");
        JPngiua.add(so11);

        so10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        so10.setText("10");
        JPngiua.add(so10);

        so9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        so9.setText("9");
        JPngiua.add(so9);

        so8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        so8.setText("8");
        JPngiua.add(so8);

        so7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        so7.setText("7");
        JPngiua.add(so7);

        so6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        so6.setText("6");
        JPngiua.add(so6);

        so5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        so5.setText("5");
        JPngiua.add(so5);

        so4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        so4.setText("4");
        JPngiua.add(so4);

        so3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        so3.setText("3");
        JPngiua.add(so3);

        so2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        so2.setText("2");
        JPngiua.add(so2);

        so1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        so1.setText("1");
        JPngiua.add(so1);

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JPngiua.add(jButton16);

        JPnmain.add(JPngiua, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPnmain, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPnmain, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTbatdauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTbatdauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBTbatdauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Thietkegiaodiengamemini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Thietkegiaodiengamemini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Thietkegiaodiengamemini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Thietkegiaodiengamemini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Thietkegiaodiengamemini().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTbatdau;
    private javax.swing.JLabel JLBname;
    private javax.swing.JPanel JPnduoi;
    private javax.swing.JPanel JPngiua;
    private javax.swing.JPanel JPnmain;
    private javax.swing.JPanel JPntren;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton so1;
    private javax.swing.JButton so10;
    private javax.swing.JButton so11;
    private javax.swing.JButton so12;
    private javax.swing.JButton so13;
    private javax.swing.JButton so14;
    private javax.swing.JButton so15;
    private javax.swing.JButton so2;
    private javax.swing.JButton so3;
    private javax.swing.JButton so4;
    private javax.swing.JButton so5;
    private javax.swing.JButton so6;
    private javax.swing.JButton so7;
    private javax.swing.JButton so8;
    private javax.swing.JButton so9;
    // End of variables declaration//GEN-END:variables
}
